# Generated by Django 4.2.20 on 2025-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
