# Generated by Django 4.2.20 on 2025-04-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_orderplaced_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='cart_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
